

export default function Body() {
    return (
        <div className="text-zinc-900 flex flex-wrap justify-center items-center font-medium p-2 m-1.5">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga eos quidem eaque voluptatum consectetur, labore, maxime nesciunt et ducimus, repellendus quae doloribus! Mollitia, nihil amet quia aliquid explicabo dolores doloremque corrupti fuga quibusdam architecto placeat voluptate asperiores. Hic, quis alias itaque voluptatem porro earum rerum reprehenderit modi ratione. Eligendi ratione odio impedit nobis adipisci reiciendis recusandae nisi obcaecati consequuntur iusto quasi in doloremque sit cupiditate ducimus rem repudiandae quaerat unde ut, cumque corporis. Saepe rem dignissimos optio magnam tempora voluptatum culpa, amet veritatis assumenda aspernatur minus quos nobis consectetur molestiae iusto quam veniam sit aut! Voluptas veniam quia hic unde ab, doloremque quidem at architecto nisi dolor numquam sint facere. Possimus dignissimos saepe totam ut, reprehenderit consequuntur placeat provident aut, eos asperiores molestias nesciunt, tempore fuga reiciendis. Quae quasi quia dolore possimus sunt! Pariatur, magnam at. Veniam repellendus illo laboriosam repudiandae repellat tempora possimus voluptatibus a distinctio quibusdam! Dignissimos obcaecati molestias quae id alias possimus. Culpa architecto aperiam optio incidunt necessitatibus non provident laudantium vero, ducimus beatae sed hic? Est incidunt corrupti atque quis. Quibusdam, iusto quos? Iste, harum, nesciunt sequi optio adipisci itaque dignissimos ex temporibus necessitatibus ullam deleniti veniam exercitationem dicta? Dolore architecto nisi dignissimos, earum iste repellat.0
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas provident debitis, natus omnis excepturi, aspernatur, nemo vero neque distinctio blanditiis beatae! Laboriosam, dicta ratione quis aliquid porro sunt facere et perspiciatis similique totam quidem delectus. Non, aperiam dolor? Modi commodi similique, minima recusandae excepturi laborum. Dolorem corrupti molestias omnis distinctio officia odio dicta facilis a at, accusantium, dolor vel adipisci eos illum? Iusto quibusdam assumenda quisquam tempora porro earum debitis consectetur maiores consequuntur ab perferendis soluta voluptate consequatur nesciunt, tempore enim sunt alias labore voluptates, dignissimos accusantium, iste dicta! Ea magni repellat quam quae, hic nulla tempore molestiae expedita error dolorum eos atque, quas quos autem numquam sunt perferendis recusandae, odit fuga natus laboriosam fugit explicabo quo quaerat. Quis provident quisquam facilis perspiciatis blanditiis, officia magni odit hic corrupti maiores molestias amet similique libero optio perferendis quam fugit, dignissimos nostrum nisi. Animi amet unde eligendi magnam doloremque quisquam! Quos necessitatibus fuga nemo earum rem nam illo eos asperiores! Distinctio consequuntur eaque, sint corporis tenetur dolore. Quam, repudiandae! Temporibus magnam rem nam beatae tempore omnis voluptas incidunt accusamus. Optio doloribus ipsum, nisi quaerat labore adipisci corporis voluptas unde ipsa quidem sunt maxime ea reprehenderit vitae ducimus aperiam dolor eaque, accusamus perspiciatis.
            </div>
    )
}